name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  js-build:
    runs-on: ubuntu-latest
    name: JS / Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run build:js

  js-lint:
    runs-on: ubuntu-latest
    name: JS / Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run lint:js

  js-test:
    runs-on: ubuntu-latest
    name: JS / Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run test -w packages/js

  svelte-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18]
        svelte-version: [^3.55.0, ^4.0.0]
    name: Svelte / Build / Svelte ${{ matrix.svelte-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm install -D svelte@${{ matrix.svelte-version }}
      - run: npm run build:js
      - run: npm run build:svelte

  svelte-lint:
    runs-on: ubuntu-latest
    name: Svelte / Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run build:js
      - run: npm run lint:svelte
