name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run test

  svelte:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.44.2', ^3.44.2, ^5.0.0-next.1]
    name: svelte@${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm i --legacy-peer-deps -D svelte@${{ matrix.version }}
      - run: npm run build
